services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb-emulator
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    volumes:
      - cosmosdb-data:/data/db
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8081/_explorer/emulator.pem"]
      interval: 30s         # give it more breathing room
      timeout: 20s
      retries: 20
      start_period: 120s
    restart: always

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite-data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 5s
      timeout: 5s
      retries: 3

  # function-app:
  #   build:
  #     context: ./DocumentVault.Functions
  #     dockerfile: Dockerfile
  #   container_name: document-vault-function
  #   restart: always
  #   depends_on:
  #     cosmosdb: 
  #       condition: service_healthy
  #     azurite:
  #       condition: service_healthy
  #   volumes:
  #     - data-protection:/root/.aspnet/DataProtection-Keys
  #   ports:
  #     - "7071:80"
  #   environment:
  #     - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
  #     - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
  #     - CosmosDb__Endpoint=https://cosmosdb:8081
  #     - CosmosDb__Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/h==
  #     - CosmosDb__DatabaseName=DocumentVaultDB
  #     - CosmosDb__LinksContainerName=Links
  #     - CosmosDb__DocumentsContainerName=documents
  #     - AZURE_COSMOS_EMULATOR_CERTIFICATE_PATH=/tmp/cosmos-cert.pem
  #     - COSMOSDB_DISABLE_SSL_VALIDATION=true
  #     - AzureWebJobsSecretStorageType=files
  #     - AzureWebJobsSecretStoragePath=/root/.aspnet/DataProtection-Keys
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/api/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 20s

  api:
    build:
      context: ./DocumentVault
      dockerfile: Dockerfile
    container_name: document-vault-api
    restart: always
    depends_on:
      cosmosdb:
        condition: service_healthy
      azurite:
        condition: service_healthy
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    ports:
      - "5000:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
        # CosmosDB Configuration - CORRECTED KEY
        - CosmosDb__Endpoint=https://cosmosdb:8081
        - CosmosDb__Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        - CosmosDb__DatabaseName=DocumentVaultDB
        - CosmosDb__LinksContainerName=Links
        - CosmosDb__DocumentsContainerName=documents
        - COSMOSDB_DISABLE_SSL_VALIDATION=true
      # Blob Storage Configuration (matches appsettings.json structure)
        - Azure__BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
        - Azure__BlobStorage__ContainerName=documents
      # Azure Functions Storage
        - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  cosmosdb-data:
  azurite-data:
  data-protection: